export default {
    attempt: 'Attempt',
    correct: 'Correct',
    default: 'Default',
    fail: 'fail',
    hours: 'hours',
    incorrect: 'Incorrect',
    minutes: 'minutes',
    noQuestionContent: 'Uh oh! There was no question content for this item.',
    pass: 'pass',
    prepare: 'Prepare',
    questions: 'questions',
    results: 'Results',
    score: 'Score',
    seconds: 'seconds',
    simulate: 'Simulate',
    skipped: 'Skipped',
    test: 'Test',
};
